name: dbc-build

on:
    push:
        branches:
            - "main"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                version: "lab:latest"
                driver: cloud
                endpoint: "dockersales/yusuf-basic-nlp"
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            
